package br.org.quilombola.enums;

import com.fasterxml.jackson.annotation.JsonFormat;

@JsonFormat(shape = JsonFormat.Shape.OBJECT)
public enum PermissoesSistemaEnum {
	
	MASTER(1),
	ADMINISTRADOR(2),
	CRUD_TERRITORIO(3),
	CRUD_MUNICIPIO(4),
	CRUD_CERTIFICADO(5),
	CRUD_COMUNIDADE(6),
	CRUD_DECRETO_DESAPROPRIATORIO(7),
	CRUD_DOCUMENTO(8),
	CRUD_EDITAL_COMUNICACAO(9),
	CRUD_MATRICULA(10),
	CRUD_ORGAO(11),
	CRUD_PORTARIA_RECONHECIMENTO(12),
	CRUD_PORTARIA(13),
	CRUD_PROCESSO_ADMINISTRATIVO(14),
	CRUD_PROCESSO_RECONHECIMENTO(15),
	CRUD_QUILOMBO(16),
	CRUD_TIPO_CONCESSAO(17),
	CRUD_TIPO_DOCUMENTO(18),
	CRUD_TITULO_PROPRIEDADE(19),
	
	READ_TERRITORIO(20),
	READ_MUNICIPIO(21),
	READ_CERTIFICADO(22),
	READ_COMUNIDADE(23),
	READ_DECRETO_DESAPROPRIATORIO(24),
	READ_DOCUMENTO(25),
	READ_EDITAL_COMUNICACAO(26),
	READ_MATRICULA(27),
	READ_ORGAO(28),
	READ_PORTARIA_RECONHECIMENTO(29),
	READ_PORTARIA(30),
	READ_PROCESSO_ADMINISTRATIVO(31),
	READ_PROCESSO_RECONHECIMENTO(32),
	READ_QUILOMBO(33),
	READ_TIPO_CONCESSAO(34),
	READ_TIPO_DOCUMENTO(35),
	READ_TITULO_PROPRIEDADE(36),
	READ_ESTADOS(37),
	READ_REGIOES(38),
	
	CRUD_SUPERINTENDENCIA(39),
	CRUD_CONTATOS(40),
	CRUD_ASSENTAMENTOS(41),
	CRUD_DADOS_ADICIONAIS(42),
	;
	
	private Integer id;
	
	private PermissoesSistemaEnum(Integer id) {
		this.id = id;
	}

	public Integer getId() {
		return id;
	}

	
}
