---
version: '3.6'
services:
  sigequi:
    container_name: quilombola
    image: quilombola:0.1.100
    ports: 
      - 8080:8080
  #  dockerfile: .
#    build: .
#      context: .
    depends_on: 
      - postgres


  postgres:
    container_name: postgres
    image: postgres:10.11
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-pX89LxzsR}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Psj1V1mep}
      PGDATA: /data/postgres
    volumes:
        - postgres:/data/postgres
    ports:
      - "5432:5432"
    command: 
      - "postgres"
      - "-c"
      - "wal_level=logical"
    restart: unless-stopped

volumes:
  postgres: